services:
  user_agent_subscriber:
    class: App\Security\BanSubscriber
    tags:
      - { name: kernel.event_subscriber }
    arguments:
      ['@security.helper', '@App\Security\UserProvider', '@security.token_storage', '@session']